### ISSUE TITLE
Undo deletes shape if created while image is loading

### ISSUE THREAD

**Issue by Taha-Hassan-Git** [tldraw/tldraw#3917]
### What happened?

On staging.tldraw.com
Undo removed two shapes that were added at different times

## Case 1:

1. Upload a big image
2. Create a shape before the image has had a chance to load
3. Wait until both shapes are on the canvas
4. Undo

Expected: One of the shapes will be removed
Actual: Both shapes are removed

## Case 2: 

1. Create a shape
2. Click the canvas to deselect the shape
3. Upload an image
4. Cmd + Z while the image is uploading, which selects the shape
5. Wait for image to load
6. undo

Expected: Remove image shape
Actual: Removes both shapes

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mimecuvalo** [comment]
Fixed by https://github.com/tldraw/tldraw/pull/3910 I believe.

**Comment by mimecuvalo** [comment]
No worries, you were clear - I think I was just overeager :)

cc @ds300 related to your work this morning?

**Comment by MitjaBezensek** [comment]
Seems like this might now be fixed? Could not reproduce it any longer, but it's a bit tricky to test so I wanted to double check.

**Comment by Taha-Hassan-Git** [comment]
It still happens, but with ghost image changes I don't think it's a problem anymore. You have to really race to draw a shape before the image appears on the canvas now. It's now a super duper edge-case, or maybe even expected behaviour.

![2024-07-23 at 11 45 18 - Yellow Pheasant](https://github.com/user-attachments/assets/06be3fa5-7218-47c4-abda-f60d423d7064)

**Comment by mimecuvalo** [comment]
Ghost image stuff hasn't landed yet - but I agree: when the ghost image stuff lands especially it'll be even better.
